[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"

[headers.values]
# X-Content-Type-Options controls whether browsers attempt to detect
# the content type, rather than relyihng on the Content-Type header.
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
X-Content-Type-Options = "nosniff"

# Strict-Transport-Security to require HTTPS connections in supported
# browsers. These settings are required to be eligible for inclusion
# in the HSTS Preload list; see: https://hstspreload.org/
Strict-Transport-Security = """\
      max-age=63072000; \
      includeSubDomains; \
      preload \
      """

# Content-Security-Policy to prevent XSS attacks.
#
# default-src
#   'self' - all resources from current origin are permitted by default
# connect-src
#   'self' - all connections to current origin are permitted
# font-src
#   'self' - all fonts from current origin are permitted
# frame-ancestors
#   'self' - allow embedding in current origin
# frame-src
#   'self' - allow embedding of current origin
# img-src
#   'self' - all images from current origin are permitted
#   data: - images embedded inline are permitted
# media-src
#   'none' - no audio or video files are permitted
# object-src
#   'none' - no legacy objects are allowed; see
#            https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/object-src
# script-src
#   'self' - all resources from current origin are permitted
# style-src
#   'self' - all styles from current origin are permitted
#   'unsafe-inline' - Styles are injected inline
Content-Security-Policy = """ \
      default-src *; \
      script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.lr-ingest.io https://js.stripe.com https://prefect.my.salesforce.com/ https://prefect.force.com/ https://prefect.my.salesforce.com https://c.la1-c2-ia2.salesforceliveagent.com/ https://d.la1-c2-ia2.salesforceliveagent.com/ https://static.lightning.force.com https://prefect--partial.my.salesforce.com https://d.la3-c1cs-ia2.salesforceliveagent.com/ https://service.force.com/ https://prefect--aleysian.my.salesforce.com https://aleysian-prefect.cs29.force.com/ https://d.la1-c2-ph2.salesforceliveagent.com/ https://partial-prefect.cs1.force.com/ https://c.la1-c1cs-ph2.salesforceliveagent.com/ https://d.la1-c1cs-ph2.salesforceliveagent.com/ https://prefect--partial.sandbox.my.salesforce.com/ https://d.la2-c1-ia5.salesforceliveagent.com https://d.la3-c1cs-ia5.salesforceliveagent.com https://prefect--partial.sandbox.my.site.com; \
      script-src-elem 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.lr-ingest.io https://js.stripe.com https://netlify-cdp-loader.netlify.app/netlify.js https://prefect.my.salesforce.com/ https://prefect.force.com/ https://prefect.my.salesforce.com https://c.la1-c2-ia2.salesforceliveagent.com/ https://d.la1-c2-ia2.salesforceliveagent.com/ https://static.lightning.force.com https://prefect--partial.my.salesforce.com https://d.la3-c1cs-ia2.salesforceliveagent.com/ https://service.force.com/ https://prefect--aleysian.my.salesforce.com https://aleysian-prefect.cs29.force.com/ https://d.la1-c2-ph2.salesforceliveagent.com/ https://partial-prefect.cs1.force.com/ https://c.la1-c1cs-ph2.salesforceliveagent.com/ https://d.la1-c1cs-ph2.salesforceliveagent.com/ https://prefect--partial.sandbox.my.salesforce.com/ https://d.la2-c1-ia5.salesforceliveagent.com https://d.la3-c1cs-ia5.salesforceliveagent.com https://prefect--partial.sandbox.my.site.com; \
      img-src * data:; \
      style-src 'self' 'unsafe-inline' https://prefect.my.salesforce.com/ https://prefect.force.com/ https://prefect.my.salesforce.com https://c.la1-c2-ia2.salesforceliveagent.com/ https://d.la1-c2-ia2.salesforceliveagent.com/ https://static.lightning.force.com https://prefect--partial.my.salesforce.com https://d.la3-c1cs-ia2.salesforceliveagent.com/ https://service.force.com/ https://prefect--aleysian.my.salesforce.com https://aleysian-prefect.cs29.force.com/ https://partial-prefect.cs1.force.com/ https://c.la1-c1cs-ph2.salesforceliveagent.com/ https://d.la1-c1cs-ph2.salesforceliveagent.com/ https://prefect--partial.sandbox.my.site.com; \
      style-src-elem 'self' 'unsafe-inline' https://prefect.my.salesforce.com/ https://prefect.force.com/ https://prefect.my.salesforce.com https://c.la1-c2-ia2.salesforceliveagent.com/ https://d.la1-c2-ia2.salesforceliveagent.com/ https://static.lightning.force.com https://prefect--partial.my.salesforce.com https://d.la3-c1cs-ia2.salesforceliveagent.com/ https://service.force.com/ https://prefect--aleysian.my.salesforce.com https://aleysian-prefect.cs29.force.com/ https://partial-prefect.cs1.force.com/ https://c.la1-c1cs-ph2.salesforceliveagent.com/ https://d.la1-c1cs-ph2.salesforceliveagent.com/ https://prefect--partial.sandbox.my.site.com; \ 
      font-src data: 'self'; \
      frame-src https://service.force.com/ https://*.prefect.io https://prefect.auth0.com https://js.stripe.com https://cloud.prefect.io https://*.okta.com https://prefect.my.salesforce.com/ https://prefect--partial.my.salesforce.com/ https://prefect--partial.sandbox.my.salesforce.com/; \
      child-src data: blob:; \
      worker-src data: blob: 'self'; \
      """

# Referrer-Policy controls the Referer header in requests.
#
# same-origin allows analytics tools to understand user journeys.
Referrer-Policy = "same-origin"

# X-Permitted-Cross-Domain-Policies controls whether this site can be
# embedded into Flash applications or PDF documents.
X-Permitted-Cross-Domain-Policies = "none"

# Permissions-Policy controls the features that the site can request.
#
# https://developer.chrome.com/en/docs/privacy-sandbox/permissions-policy/
# https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md
Permissions-Policy = """\
      accelerometer=(), \
      ambient-light-sensor=(), \
      autoplay=(), \
      battery=(), \
      camera=(), \
      cross-origin-isolated=(), \
      display-capture=(), \
      document-domain=(), \
      encrypted-media=(), \
      execution-while-not-rendered=(), \
      execution-while-out-of-viewport=(), \
      fullscreen=(), \
      geolocation=(), \
      gyroscope=(), \
      hid=(), \
      idle-detection=(), \
      magnetometer=(), \
      microphone=(), \
      midi=(), \
      navigation-override=(), \
      payment=(), \
      picture-in-picture=(), \
      publickey-credentials-get=(), \
      screen-wake-lock=(), \
      serial=(), \
      sync-xhr=(), \
      usb=(), \
      web-share=(), \
      xr-spatial-tracking=() \
      """
