query FailedTasks($heartbeat: timestamptz) {
  task_run(
    where: { state: { _eq: "Failed" }, updated: { _gte: $heartbeat } }
    distinct_on: task_id
  ) {
    id
    task {
      id
      name
      flow {
        name
      }
    }
  }
}
