query ($heartbeat: timestamptz) {
  task_run
    (where: {
        _and: [{
            state: {
              _eq: "Failed"
            }
          },
          {
            updated: {
              _gte: $heartbeat
            }
          }
        ]
      }
      distinct_on: task_id) {
      id
      task {
        id
        name
      }
    }
}