query Failures($heartbeat: timestamptz, $projectId: UUID) {
  flow_run(
    where: {
      updated: { _gte: $heartbeat }
      flow: { project_id: { _eq: $projectId } }
      logs: { level: { _in: ["CRITICAL", "ERROR"] } }
    }
    distinct_on: flow_id
    order_by: [{ flow_id: asc }, { updated: desc }]
  ) {
    id
    name
    logs(
      limit: 1
      where: {
        level: { _in: ["CRITICAL", "ERROR"] }
        timestamp: { _gte: $heartbeat }
      }
    ) {
      id
      level
      message
      name
      timestamp
    }

    flow {
      id
      name
    }
  }
}
