query FailureCount($heartbeat: timestamptz, $projectId: UUID) {
  flow_aggregate(
    where: {
      flow_runs: { state: { _eq: "Failed" }, updated: { _gte: $heartbeat } }
      project_id: { _eq: $projectId }
    }
  ) {
    aggregate {
      count
    }
  }
}
