query FlowRunsCount($projectIds: [UUID!], $heartbeat: timestamptz) {
  flow_run_aggregate(
    where: {
      flow: { project_id: { _in: $projectIds } }
      updated: { _gte: $heartbeat }
      state: { _neq: "Scheduled" }
    }
  ) {
    aggregate {
      count
    }
  }
}
