query FlowCount(
  $projectId: UUID
  $archived: Boolean
  $searchParams: [flow_bool_exp!]
) {
  flowCount: flow_aggregate(
    where: {
      project_id: { _eq: $projectId }
      archived: { _eq: $archived }
      _or: $searchParams
    }
  ) {
    aggregate {
      count
    }
  }
}
