query FlowFailures($projectId: uuid, $heartbeat: timestamptz, $tenantId: uuid) {
  flow_run(
    where: {
      tenant_id: { _eq: $tenantId }
      flow: { project_id: { _eq: $projectId } }
      state: { _eq: "Failed" }
      start_time: { _gte: $heartbeat }
    }
    distinct_on: flow_id
    order_by: { flow_id: asc, start_time: desc }
  ) {
    flow_id
    state_timestamp

    flow {
      id
      name
      flow_group_id
    }

    start_time
  }
}
