query FlowCount(
  $projectId: uuid
  $archived: Boolean
  $searchParams: [flow_group_bool_exp!]
) {
  flowCount: flow_group_aggregate(
    where: {
      flows: { project_id: { _eq: $projectId }, archived: { _eq: $archived } }
      _or: $searchParams
    }
  ) {
    aggregate {
      count
    }
  }
}
