query LastFlowRuns($flowId: uuid!) {
  flow_run(
    where: { flow_id: { _eq: $flowId }, state: { _neq: "Scheduled" } }
    limit: 10
    order_by: { start_time: asc }
  ) {
    id
    end_time
    flow_id
    start_time
    state
  }
}
