query FailedTasks($heartbeat: timestamptz, $tenantId: uuid!) {
  task_run(
    where: {
      state: { _eq: "Failed" }
      updated: { _gte: $heartbeat }
      tenant_id: { _eq: $tenantId }
    }
    distinct_on: task_id
  ) {
    id
    updated
    task {
      id
      name
      flow {
        name
      }
    }
  }
}
