query Usage($from: timestamptz, $to: timestamptz, $tenant_id: uuid) {
  usage: billing_usage(
    where: {
      timestamp: { _gte: $from, _lte: $to }
      tenant_id: { _eq: $tenant_id }
    }
  ) {
    id
    kind
    runs
    tenant_id
    timestamp
    usage_last_updated
  }
}
