query billingLicense($id: uuid!) {
  billing_license(where: { tenant_id: { _eq: $id } }) {
    active
    created
    end_date
    id
    name
    product
    start_date
    status
    tenant_id
    trial_end_date
    type
  }
}
