query Memberships($id: UUID) {
  membership_invitation(where: { id: { _eq: $id } }) {
    created
    email
    id
    role
    tenant {
      name
    }
    user {
      username
      email
    }
    tenant_id
  }
}
