query Memberships($id: uuid) {
  membership_invitation(where: { id: { _eq: $id } }) {
    id
    created
    email
    role
    tenant {
      id
      name
      slug
    }
    user {
      id
      username
      email
    }
    tenant_id
  }
}
