query Membership($membershipId: UUID!) {
  membership(where: { id: { _eq: $membershipId } }) {
    id
    role
    tenant {
      id
      name
      slug
      settings
      stripe_customer
      prefectAdminSettings: prefect_admin_settings
    }
  }
}
