query PendingInvitations($email: String!, $tenantIds: [uuid!]) {
  pendingInvitations: membership_invitation(
    where: { _and: [
      { email: { _eq: $email }},
      {tenant_id: {_nin: $tenantIds}} ]}
  ) {
    tenant_id
    id
    role
    email
    created
    tenant {
      id
      name
      slug
    }
  }
}
