query TenantUsers {
  tenantUsers: user_view_same_tenant {
    id
    username
    email
    first_name
    last_name
    memberships {
      id
      tenant_id
      role_detail {
        id
        name
      }
    }
  }
}
