mutation UpdateTenant($name: String!, $slug: String!) {
  updateTenantName(input: { name: $name }) {
    tenant {
      id
      slug
      name
    }
  }
  updateTenantSlug(input: { slug: $slug }) {
    tenant {
      id
      slug
      name
      memberships {
        id
      }
    }
  }
}
