query ($tenantId: uuid) {
  pendingInvitations:tenant
    (where: {
      id: {
        _eq: $tenantId
      }
    }) {
      membership_invitations_aggregate {
        aggregate {
          count
        }
      }
    }
}