query UpcomingFlowRunsDrawerCount($projectIds: [uuid!], $flowId: uuid) {
  flow_run_aggregate(
    where: {
      flow_id: { _eq: $flowId }
      flow: { project_id: { _in: $projectIds } }
      state: { _eq: "Scheduled" }
    }
  ) {
    aggregate {
      count
    }
  }
}
