query DataToClear {
  memberships: user_view_same_tenant {
    id
    memberships {
      id
    }
  }

  membershipInvitations: membership_invitation {
    id
  }

  project {
    id
  }

  flow(distinct_on: version_group_id, where: { archived: { _eq: false } }) {
    id
  }

  secret_names

  api_token {
    id
  }
}
