query FlowVersionGroups {
  versionGroup: flow(distinct_on: [version_group_id]) {
    version_group_id
    id
    name
    project {
      id
      name
    }
    created_by {
      id
      username
    }
  }
}
