mutation ModifyProject(
  $projectId: uuid!
  $projectName: String!
  $projectDescription: String
) {
  set_project_name(input: { project_id: $projectId, name: $projectName }) {
    id
  }

  set_project_description(
    input: { project_id: $projectId, description: $projectDescription }
  ) {
    id
  }
}
