query($flowRunId: UUID, $taskId: UUID) {
  task_run(
    where: {
      _and: [
        { flow_run: { id: { _eq: $flowRunId } } }
        { task_id: { _eq: $taskId } }
      ]
    }
  ) {
    id
  }
}
