query taskRunParent($flowRunId: uuid, $taskId: uuid) {
  task_run(
    where: {
      _and: [
        { flow_run_id: { _eq: $flowRunId } }
        { task_id: { _eq: $taskId } }
      ]
    }
  ) {
    id
  }
}
