query TaskRun($id: uuid!) {
  task_run_by_pk(id: $id) {
    id
    version
    state
    state_message
    state_timestamp
    updated
    start_time
    end_time
    map_index
    serialized_state
    name

    task {
      id
      name
      retry_delay
      max_retries
      trigger
      type

      upstream_edges {
        upstream_task {
          id
          name
        }
        downstream_task {
          id
          name
        }
      }
      downstream_edges {
        upstream_task {
          id
          name
        }
        downstream_task {
          id
          name
        }
      }
    }

    flow_run {
      id
      name
      state
      flow {
        id
        flow_group_id
        name
        project {
          id
          name
        }
      }
      parameters
      version
    }
  }
}
