query LastTaskRun($id: uuid!) {
  task_run(
    where: {
      task_id: { _eq: $id }
      state: { _neq: "Scheduled" }
      start_time: { _is_null: false }
    }
    order_by: { updated: desc }
    limit: 1
  ) {
    id
    state
  }
}
