query Task($id: uuid!) {
  task_by_pk(id: $id) {
    id
    name
    description
    created
    retry_delay
    max_retries
    trigger
    type

    upstream_edges {
      id
      upstream_task {
        id
        name
        retry_delay
        max_retries
        trigger
        type
      }
    }
    downstream_edges {
      id
      downstream_task {
        id
        name
        retry_delay
        max_retries
        trigger
        type
      }
    }

    flow {
      id
      flow_group_id
      name
      version
      project {
        id
        name
      }
      parameters
    }
  }
}
