query Errors(
  $updated: timestamptz_comparison_exp
  $flow_group_id: uuid
  $flow_id: uuid
) {
  flow_run(
    where: {
      updated: $updated
      flow: { id: { _eq: $flow_id }, flow_group_id: { _eq: $flow_group_id } }
    }
    limit: 50
    order_by: [{ updated: desc }]
  ) {
    id
    name
    task_runs(where: { state: { _eq: "Failed" } }){
        task{
            id
            name
        }
        id
        state_message
        state_timestamp
    }
  }
}
