query Flow($id: UUID!) {
  flow_group_by_pk(id: $id) {
    id

    created
    name

    schedule

    flows {
      id

      archived
      core_version
      created

      created_by {
        username
      }

      description
      environment
      flow_group_id

      is_schedule_active

      name
      parameters

      project {
        id
        name
      }

      schedule

      storage

      updated
      version
      version_group_id
    }

    settings
    updated
  }
}
