query VersionsCount($flow_group_id: uuid!, $search: Int) {
  flow_group_by_pk(id: $flow_group_id) {
    id

    flows_aggregate(where: { version: { _eq: $search } }) {
      aggregate {
        count
      }
    }
  }
}
