query PastFlowRuns($id: UUID!, $heartbeat: timestamptz) {
  flow_run(
    where: {
      flow_id: { _eq: $id }
      updated: { _gte: $heartbeat }
      state: { _neq: "Scheduled" }
    }
    order_by: { scheduled_start_time: desc }
  ) {
    id
    state
  }
}
