query TableFlowRunsCount(
  $flow_group_id: uuid
  $flow_id: uuid
  $name: String
  $state: [String!]
) {
  flow_run_aggregate(
    where: {
      flow: { flow_group_id: { _eq: $flow_group_id }, id: { _eq: $flow_id } }
      name: { _ilike: $name }
      state: { _in: $state }
    }
  ) {
    aggregate {
      count
    }
  }
}
