query TableFlowRuns(
  $name: String
  $limit: Int
  $offset: Int
  $orderBy: [flow_run_order_by!]
  $flow_group_id: uuid
  $flow_id: uuid
  $state: [String!]
) {
  flow_run(
    where: {
      flow: { flow_group_id: { _eq: $flow_group_id }, id: { _eq: $flow_id } }
      name: { _ilike: $name }
      state: { _in: $state }
    }
    order_by: $orderBy
    limit: $limit
    offset: $offset
  ) {
    id
    name
    end_time
    scheduled_start_time
    start_time
    state
  }
}
