export const faAws: IconDefinition;
export const faCcAmazonPay: IconDefinition;
export const faCcAmex: IconDefinition;
export const faCcApplePay: IconDefinition;
export const faCcDinersClub: IconDefinition;
export const faCcDiscover: IconDefinition;
export const faCcJcb: IconDefinition;
export const faCcMastercard: IconDefinition;
export const faCcPaypal: IconDefinition;
export const faCcStripe: IconDefinition;
export const faCcVisa: IconDefinition;
export const faDiscourse: IconDefinition;
export const faDocker: IconDefinition;
export const faGithub: IconDefinition;
export const faInstagram: IconDefinition;
export const faMicrosoft: IconDefinition;
export const faRev: IconDefinition;
export const faSlack: IconDefinition;
export const faTwitter: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const fab: IconPack;