query FailedTaskRuns($flowRunId: uuid, $failedStates: [String!]) {
  task_run(
    where: {
      flow_run_id: { _eq: $flowRunId }
      state: { _in: $failedStates }
    }
  ) {
    id
    task_id
    version
  }
}
