query TableTaskRuns(
  $flowRunId: uuid
  $run_name: String
  $state: [String!]
  $limit: Int
  $offset: Int
  $orderBy: [task_run_order_by!]
) {
  flow_run(where: { id: { _eq: $flowRunId } }) {
    id
    name
    task_runs(
      where: {
        _or: [
          { name: { _ilike: $run_name } }
          { task: { name: { _ilike: $run_name } } }
        ]
        state: { _in: $state }
      }
      order_by: $orderBy
      limit: $limit
      offset: $offset
    ) {
      map_index
      state
      id
      version
      start_time
      end_time

      task {
        id
        name
      }
      name
    }
  }
}
