query TableTaskRunsCount(
  $flowRunId: uuid
  $name: String
  $state: [String!]
  $heartbeat: timestamptz
) {
  task_run_aggregate(
    where: {

      flow_run_id: { _eq: $flowRunId }
      _or: [{name: {_ilike: $name}}, { task: { name: { _ilike: $name } }, state: { _in: $state } }]
      updated: { _gte: $heartbeat }
    }
  ) {
    aggregate {
      count
    }
  }
}
