query TableTaskRunsCount(
  $flowRunId: UUID
  $name: String
  $heartbeat: timestamptz
) {
  task_run_aggregate(
    where: {
      flow_run_id: { _eq: $flowRunId }
      _or: [{ task: { name: { _ilike: $name } } }]
      updated: { _gte: $heartbeat }
    }
  ) {
    aggregate {
      count
    }
  }
}
