query TableTaskRuns(
  $flowRunId: uuid
  $name: String
  $state: [String!]
  $limit: Int
  $offset: Int
  $orderBy: [task_run_order_by!]
) {
  flow_run(where: { id: { _eq: $flowRunId } }) {
    id
    name
    task_runs(
      where: { task: { name: { _ilike: $name } }, state: { _in: $state } }
      order_by: $orderBy
      limit: $limit
      offset: $offset
    ) {
      map_index
      state
      details {
        end_time
        start_time
        id
        version
      }
      task {
        id
        name
      }
      name
    }
  }
}
