query taskRunIds($flowRunId: uuid!, $parentMapIndex: Int, $childMapIndex: Int) {
  task_run(
    where: {
      _and: [
        { flow_run_id: { _eq: $flowRunId } }
        { map_index: { _eq: $parentMapIndex } }
        { map_index: { _gte: $childMapIndex } }
      ]
    }
  ) {
    version
    id
    map_index
  }
}
