query TaskRuns($flowRunId: uuid!) {
  task_run(
    where: { flow_run_id: { _eq: $flowRunId }, map_index: { _eq: -1 } }
  ) {
    id
    start_time
    end_time
    name
    serialized_state
    state
    state_timestamp

    states {
      id
      message
      state
      timestamp
      start_time
    }

    task_id
    version
  }
}
