query APITokens {
  api_token(
    order_by: { created: desc }
    where: { scope: { _in: ["TENANT", "RUNNER"] } }
  ) {
    id
    name
    created_by {
      username
    }
    created
    expires_at
    last_used
    tenant_id
    user_id
    scope
  }
}
