query APIKeys {
  auth_api_key(order_by: { created: desc }) {
    id
    name
    created
    expires_at
    default_tenant_id
    user_id
    updated

    created_by {
      id
      username
    }
  }
}
