query CalendarRunningFlowRuns {
  flow_group {
    id
    name
    flows {
      name
      id
      version
      flow_runs (where: {state:{_eq: "Running"}}){
        id
        name
        start_time
    }
  }
}
}
