query CalendarFlowRuns($startTime: timestamptz, $endTime: timestamptz) {
  flow_run (
    where: { 
      _and: [
    {start_time: { _gt: $startTime}}, 
    {start_time: { _lt: $endTime}}
      ]
    }
  ) 
  {
    id
    flow_id
    flow {
      id
      name
      version
    }
  }
}