query CalendarFlowRuns($startTime: timestamptz, $endTime: timestamptz) {
  flow_run (
    where: { 
      _and: [
    {start_time: { _gt: $startTime}}, 
    {start_time: { _lt: $endTime}}
      ]
    }
    distinct_on: flow_id
    limit: 1
  ) 
  {
    id
    flow_id
  }
}