query CalendarFlowRuns($project_id: uuid, $startTime: timestamptz, $endTime: timestamptz, $flowIds: [uuid!]) {
  flow_run (
    where: { 
      _and: [
    {flow: { project_id: { _eq: $project_id } }}
    {flow: {flow_group_id: { _in: $flowIds}}}
    {start_time: { _gt: $startTime}}, 
    {start_time: { _lt: $endTime}}
      ]
    }
  ) 
  {
    id
    flow_id
    flow {
      flow_group_id
      id
      name
      version
    }
    name
    end_time
    start_time
    scheduled_start_time
    state
  }
}
