query CalendarRunningFlowRuns ($startTime: timestamptz) {
  flow_group {
    id
    name
    flows {
      name
      id
      version
      flow_runs (where: {_and:[{state:{_eq: "Running"}}, {start_time: {_lt: $startTime}}]}){
        id
        name
        state
        start_time
    }
  }
}
}
