query CalendarDayOngoingFlowRuns($flowId: uuid!, $startTime:timestamptz, $endTime: timestamptz) {
  flow_run (
    where: { 
      _and: [
    {flow_id: { _eq: $flowId}},
    {start_time: {_lt: $startTime}}
    {end_time: {_gt: $endTime}}
      ]
    }
  ) 
  {
    id
    flow_id
    name
    end_time
    start_time
    scheduled_start_time
    state
  }
}