query CalendarScheduledFlowRuns($startTime: timestamptz) {
  flow_group {
    id
    name
    flows {
      name
      version
      id
      flow_runs (where: { 
      _and: [
    {scheduled_start_time: { _gt: $startTime}},
    {scheduled_start_time: { _lt: $endTime}},
    {state: {_eq: "Scheduled"}}
    ]
    }
  ) {
        id
        name
        state
        scheduled_start_time
    }
  }
}
}
