export const faCheckCircle: IconDefinition;
export const faDesktop: IconDefinition;
export const faEye: IconDefinition;
export const faFileCode: IconDefinition;
export const faInfo: IconDefinition;
export const faInfoCircle: IconDefinition;
export const faPlus: IconDefinition;
export const faQuestionCircle: IconDefinition;
export const faRocket: IconDefinition;
export const faSave: IconDefinition;
export const faSlash: IconDefinition;
export const faTimes: IconDefinition;
export const faUndo: IconDefinition;
export const faUndoAlt: IconDefinition;
export const faUser: IconDefinition;
export const faUserFriends: IconDefinition;
export const faUsers: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const far: IconPack;