query Task($id: uuid!) {
  task(where: { id: { _eq: $id } }) {
    id
    name
    downstream_edges {
      id
      downstream_task_id
    }
    upstream_edges {
      id
      upstream_task_id
    }
    slug
    tags
    type
    trigger
    description
    auto_generated
    __typename
  }
}
